@extends('layouts.app')

@section('title', 'Users - Vendor Portal')

@push('head')
<link href="{{ asset('css/admin-users.css') }}" rel="stylesheet">
@endpush

@section('content')
<!-- Page Header -->
<div class="page-header">
    <h1 class="page-title">User Management</h1>
    <p class="page-subtitle">Manage your team members and their account permissions here.</p>
</div>

<!-- Toolbar -->
<div class="toolbar">
    <div class="user-count">
        All users <span id="totalCount">0</span>
    </div>
    <div class="toolbar-actions">
        <div class="search-box">
            <i class="bi bi-search"></i>
            <input type="text" id="searchInput" placeholder="Search">
        </div>
        
        <!-- Filter Dropdown -->
        <div class="filter-dropdown-container">
            <button class="btn-filter" id="filterBtn">
                <i class="bi bi-funnel"></i> Filters
            </button>
            <div class="filter-dropdown" id="filterDropdown">
                <div class="filter-dropdown-header">Filter by Status</div>
                <div class="filter-dropdown-item active" data-filter="all">
                    <i class="bi bi-people"></i> All Users
                </div>
                <div class="filter-dropdown-item" data-filter="active">
                    <i class="bi bi-check-circle"></i> Active Only
                </div>
                <div class="filter-dropdown-item" data-filter="inactive">
                    <i class="bi bi-x-circle"></i> Inactive Only
                </div>
            </div>
        </div>
        
        <button class="btn-add" data-bs-toggle="modal" data-bs-target="#userModal" onclick="openCreateModal()">
            <i class="bi bi-plus"></i> Add user
        </button>
    </div>
</div>

<!-- Table Container -->
<div class="table-container">
    <table class="users-table" id="usersTable">
        <thead>
            <tr>
                <th>User name</th>
                <th>Role</th>
                <th>Status</th>
                <th>Last active</th>
                <th>Date added</th>
                <th width="50"></th>
            </tr>
        </thead>
        <tbody id="usersTableBody">
            <!-- Data loaded via JS -->
        </tbody>
    </table>
    
    <!-- Pagination -->
    <div class="pagination-container" id="pagination">
        <!-- Generated by JS -->
    </div>
</div>

<!-- User Modal (Create/Edit) -->
<div class="modal fade" id="userModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="userModalTitle">Add New User</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <form id="userForm">
                    <input type="hidden" id="userId" value="">
                    
                    <div class="mb-3">
                        <label class="form-label">Full Name <span class="text-danger">*</span></label>
                        <input type="text" class="form-control" id="userName" placeholder="Enter full name" required>
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Email Address <span class="text-danger">*</span></label>
                        <input type="email" class="form-control" id="userEmail" placeholder="Enter email address" required>
                    </div>

                    <div class="mb-3">
                        <label class="form-label">Password <span class="text-danger" id="passwordRequired">*</span></label>
                        <input type="password" class="form-control" id="userPassword" placeholder="Enter password">
                        <small class="text-muted" id="passwordHint" style="display: none;">Leave blank to keep current password</small>
                    </div>

                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label class="form-label">Role <span class="text-danger">*</span></label>
                            <select class="form-select" id="userRole" required>
                                <option value="">Select Role</option>
                            </select>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="form-label">Status <span class="text-danger">*</span></label>
                            <select class="form-select" id="userStatus" required>
                                <option value="active">Active</option>
                                <option value="inactive">Inactive</option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" onclick="saveUser()">
                    <span id="saveButtonText">Save User</span>
                </button>
            </div>
        </div>
    </div>
</div>

<!-- View User Modal -->
<div class="modal fade" id="viewUserModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">User Details</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <table class="table view-table">
                    <tr>
                        <th>Full Name</th>
                        <td id="viewName"></td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td id="viewEmail"></td>
                    </tr>
                    <tr>
                        <th>Role</th>
                        <td id="viewRole"></td>
                    </tr>
                    <tr>
                        <th>Status</th>
                        <td id="viewStatus"></td>
                    </tr>
                    <tr>
                        <th>Created</th>
                        <td id="viewCreatedAt"></td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Toast Notification -->
<div class="toast-notification" id="toastNotification">
    <i class="bi bi-check-circle-fill toast-icon success"></i>
    <span class="toast-message" id="toastMessage">Success</span>
    <i class="bi bi-x toast-close" onclick="hideToast()"></i>
</div>
@endsection

@push('scripts')
<script src="{{ asset('js/admin-users.js') }}"></script>
@endpush