@extends('layouts.app')

@section('title', 'Roles & Permissions - Vendor Portal')

@push('head')
<link href="{{ asset('css/admin-roles.css') }}" rel="stylesheet">
@endpush

@section('content')
<!-- Page Header -->
<div class="page-header">
    <h1 class="page-title">Roles & Permissions</h1>
    <p class="page-subtitle">Manage roles and their permissions for your team members.</p>
</div>

<!-- Toolbar -->
<div class="toolbar">
    <div class="role-count">
        All roles <span id="totalCount">0</span>
    </div>
    <div class="toolbar-actions">
        <div class="search-box">
            <i class="bi bi-search"></i>
            <input type="text" id="searchInput" placeholder="Search roles">
        </div>
        <button class="btn-add" onclick="openCreateModal()">
            <i class="bi bi-plus"></i> Add role
        </button>
    </div>
</div>

<!-- Table Container -->
<div class="table-container">
    <table class="roles-table" id="rolesTable">
        <thead>
            <tr>
                <th>Role</th>
                <th>Permissions</th>
                <th>Users</th>
                <th>Type</th>
                <th width="50"></th>
            </tr>
        </thead>
        <tbody id="rolesTableBody">
            <!-- Data loaded via JS -->
        </tbody>
    </table>
    
    <!-- Pagination -->
    <div class="pagination-container" id="pagination">
        <!-- Generated by JS -->
    </div>
</div>

<!-- Role Modal (Create/Edit) -->
<div class="modal fade" id="roleModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="roleModalTitle">Create New Role</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <form id="roleForm">
                    <input type="hidden" id="roleId" value="">
                    
                    <div class="row mb-4">
                        <div class="col-md-6 mb-3 mb-md-0">
                            <label class="form-label">Role Name <span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="roleName" placeholder="e.g. Manager" required>
                        </div>
                        <div class="col-md-6">
                            <label class="form-label">Description</label>
                            <input type="text" class="form-control" id="roleDescription" placeholder="Brief description">
                        </div>
                    </div>

                    <!-- Select All -->
                    <div class="select-all-box">
                        <input type="checkbox" id="selectAllPermissions" onchange="toggleAllPermissions(this.checked)">
                        <label for="selectAllPermissions">Select All Permissions</label>
                    </div>

                    <!-- Permissions -->
                    <div id="permissionsContainer">
                        <!-- Permissions loaded via JS -->
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" onclick="saveRole()">
                    <span id="saveButtonText">Create Role</span>
                </button>
            </div>
        </div>
    </div>
</div>

<!-- View Role Modal -->
<div class="modal fade" id="viewRoleModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Role Details</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <div class="view-role-header">
                    <div class="view-role-icon">
                        <i class="bi bi-shield-check"></i>
                    </div>
                    <h4 class="view-role-name" id="viewRoleName"></h4>
                    <p class="view-role-desc" id="viewRoleDesc"></p>
                    <div class="view-role-meta">
                        <span class="view-meta-item">
                            <i class="bi bi-people"></i> <span id="viewUsersCount">0</span> Users
                        </span>
                        <span class="view-meta-item">
                            <i class="bi bi-key"></i> <span id="viewPermsCount">0</span> Permissions
                        </span>
                    </div>
                </div>
                
                <div class="view-permissions-title">
                    <i class="bi bi-key"></i> Assigned Permissions
                </div>
                <div class="view-permissions-grid" id="viewPermissions">
                    <!-- Permissions loaded here -->
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="delete-modal-body">
                    <div class="delete-icon">
                        <i class="bi bi-trash"></i>
                    </div>
                    <h5 class="delete-title">Delete Role?</h5>
                    <p class="delete-text">This action cannot be undone. Users with this role will lose access.</p>
                    <input type="hidden" id="deleteRoleId">
                </div>
            </div>
            <div class="modal-footer justify-content-center border-0 pt-0">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" onclick="confirmDelete()">Delete</button>
            </div>
        </div>
    </div>
</div>

<!-- Toast Notification -->
<div class="toast-notification" id="toastNotification">
    <i class="bi bi-check-circle-fill toast-icon success"></i>
    <span class="toast-message" id="toastMessage">Success</span>
    <i class="bi bi-x toast-close" onclick="hideToast()"></i>
</div>
@endsection

@push('scripts')
<script src="{{ asset('js/admin-roles.js') }}"></script>
@endpush
